### ISSUE TITLE
如何运行fetchTE.py只爬取每周weekly edition板块的内容？程序中好像与fetchSection('teaser-weekly-edition--cols',docu)相关，请问如何具体操作，谢谢

### ISSUE THREAD

**Issue by Monkfishare** [taizihuang/TheEconomist#2]

**Comment by taizihuang** [comment]
`fetchSection()` 是提取docu中文章的链接，比如cols就是各个板块（US/China/Asia等等），leaders是社论。我猜你说的"每周weekly edition板块"应该是每周的内容？那么执行 `python fetchTE.py` 就可以爬取每周最新的，往期的你只需要修改`url = "https://www.economist.com/weeklyedition/"`链接到历史期刊的链接就好了。不过你要注意：

1. 如果你在国内需要挂代理；
3. 代码写得很粗糙，所以我时不时要小修小补。然后有些页面为了偷懒就直接跳过（比如economic indicator，ukraine相关），有问题你可以再提；
4. 我每周会更新PDF版本，链接在README中，你试试看。

**Comment by AlexHenry666** [comment]
根据描述，fetchSection()貌似提取了html文本中引用的所有链接。

开代理运行代码`py fetchTE.py`，一看文件夹里最新保存了200+个html文章，还有2021，2022年的。而实际最新一期的weekly-edition文章不到80，日期是最近一周的。

若只想爬取https://www.economist.com/weeklyedition/archive中最新一周的80个html，请问需要如何运行或修改相关代码？
以及html如何转换成google drive中所提供的PDF样式？

谢谢解答

**Comment by AlexHenry666** [comment]
能否考虑添加多线程爬取功能，节省时间

**Comment by taizihuang** [comment]
> 一看文件夹里最新保存了200+个html文章，还有2021，2022年的。

很多文章内引用了往期内容，我一并下载下来，这样浏览的时候不需要跳转到原网址。你只需要修改第4行为`def fetchArticle(link,n=0):`即可去掉这个功能。

> html如何转换成google drive中所提供的PDF样式？

你打开 `TheEconomist/html/concat.html`页面，然后打印该页面（按F12开控制台执行`document.querySelectorAll(".css-1lm38nn.e1lug06p0").forEach(el => el.remove());`可以把播放栏删掉）。我选择的格式是 90%缩放，双页并排打印。

> 能否考虑添加多线程爬取功能，节省时间

我可以加，只是现在没有太多时间。你可以尝试放在Github Actions上面每周自动下载。

**Comment by AlexHenry666** [comment]
https://www.economist.com/the-world-this-week/2023/06/01/politics
https://www.economist.com/the-world-this-week/2023/06/01/business
...
https://www.economist.com/the-economist-explains/2023/05/31/what-does-de-risking-trade-with-china-mean
https://www.economist.com/obituary/2023/06/01/tina-turner-turned-a-tough-life-into-splendour
Traceback (most recent call last):
  File "C:\Users\18372\Desktop\TheEconomist-main\fetchTE.py", line 263, in <module>
    genPrint()
  File "C:\Users\18372\Desktop\TheEconomist-main\fetchTE.py", line 216, in genPrint
    with open('file_name.html', 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'file_name.html'

进程已结束,退出代码1

- 代码按照`def fetchArticle(link,n=0):`修改后，运行`fetchTE.py`程序，顺利生成预期html。
- 出现如上报错，查看对应文件夹没生成新的concat.html文件。
- 感谢耐心解答

**Comment by taizihuang** [comment]
> `with open('file_name.html', 'r', encoding='utf-8') as f:`

你这里是不是改了？我原来写的是`index.html`，也就是先读取index.html里面的文章链接，然后拼成一个网页。

**Comment by AlexHenry666** [comment]
已将代码内容按照最新上传的fetch.py更新，file_name.html已修改为index.html
出现如下编码报错：
Traceback (most recent call last):
  File "C:\Users\18372\Desktop\TheEconomist-main\fetchTE.py", line 285, in <module>
    genPrint()
  File "C:\Users\18372\Desktop\TheEconomist-main\fetchTE.py", line 236, in genPrint
    doc_index = BeautifulSoup(f.read())
                              ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 2059: invalid start byte

**Comment by taizihuang** [comment]
你这个报错比较奇怪，因为生成的网页都是utf8编码的，不太可能读不了。你Google看看换encoding可不可以。

genPrint()这个函数可以单拎出来执行，不需要把之前下载好的再下载一遍。

**Comment by AlexHenry666** [comment]
将encoding换成gbk，解决了问题。特意查看index.html中position2059居然是中文标点：`'`撇号，上下文为`KAL's cartoon`。最终代码成功运行，感谢一直耐心的解答。

genPrint()如何单独运行？能够具体说明吗

**Comment by taizihuang** [comment]
这是python最基础的function用法，所以很容易就能自己找到答案。

**Comment by AlexHenry666** [comment]
https://www.economist.com/leaders/2023/06/08/ukraine-strikes-back

https://www.economist.com/briefing/2023/06/07/ukraines-counter-offensive-is-gathering-pace

https://www.economist.com/briefing/2023/06/06/the-geopolitical-stakes-of-ukraines-counter-offensive

https://www.economist.com/briefing/2023/06/08/pretending-that-everything-is-under-control-in-russia

https://www.economist.com/europe/2023/06/07/russias-war-on-ukraine-is-changing-europe

发现以上只爬取了标题，正文部分缺失。相似点都是ukraine主题，正文中含有米色书签栏。

**Comment by AlexHenry666** [comment]
> html如何转换成google drive中所提供的PDF样式？
>
> 你打开 `TheEconomist/html/concat.html`页面，然后打印该页面（按F12开控制台执行`document.querySelectorAll(".css-1lm38nn.e1lug06p0").forEach(el => el.remove());`可以把播放栏删掉）。我选择的格式是 90%缩放，双页并排打印。

1. 在原基础更新JS样式：

`document.querySelectorAll(".css-1lm38nn.e1lug06p0, p.article__body-text iframe[src^=\'https://www.youtube.com/embed/\']").forEach(el => el.remove());`

其中`p.article__body-text iframe[src^=\'https://www.youtube.com/embed/\']`为html内嵌视频样式

2. 请教一下， 如何单独生成index.html文件，可以根据weeklyedition自定义修改

**Comment by taizihuang** [comment]
> 发现以上只爬取了标题，正文部分缺失。相似点都是ukraine主题，正文中含有米色书签栏。

已经更新`fetchTE.py`，修复了这个bug。

> 请教一下， 如何单独生成index.html文件

把所有的`fetchSection()`注释掉就好了。

**Comment by AlexHenry666** [comment]
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/b0d9ac0b-fc49-457e-81ce-4069eaa3d868)
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/f69a849c-7924-4a95-aceb-463a96ab7625)
引用自https://www.economist.com/finance-and-economics/2023/06/08/amoral-cities-are-flourishing-in-a-turbulent-geopolitical-era
打印时在`选项`中勾选`背景图形`，能够`彩色`显示这种特殊图片

**Comment by taizihuang** [comment]
> 正文中含有交互式图表，一直报错如下，更换多个代理节点测试，问题依旧

你只要Google一下，就能找到解答。

> 打印时在选项中勾选背景图形，能够彩色显示这种特殊图片

然后？

**Comment by AlexHenry666** [comment]
> ![image](https://user-images.githubusercontent.com/50627932/245140153-b0d9ac0b-fc49-457e-81ce-4069eaa3d868.png) ![image](https://user-images.githubusercontent.com/50627932/245139076-f69a849c-7924-4a95-aceb-463a96ab7625.png) 引用自https://www.economist.com/finance-and-economics/2023/06/08/amoral-cities-are-flourishing-in-a-turbulent-geopolitical-era 打印时在`选项`中勾选`背景图形`，能够`彩色`显示这种特殊图片

然后导出的PDF中这种图片就会彩色显示，而不是黑白。一般情况是不需要勾选`背景图形`，但这种图片不勾选就没法在PDF中显示原本的颜色。

**Comment by taizihuang** [comment]
> 报错的原因是无法下载`https://tags.tiqcdn.com/utag/teg/core/prod/utag.js`这个文件。你试试在代码中加上下面几行，开启全局代理：
```python
import os
os.environ['http_proxy'] = 'http://127.0.0.1:10809'
os.environ['https_proxy'] = 'http://127.0.0.1:10809'
```

**Comment by AlexHenry666** [comment]
谢谢
还是一样的报错😹

**Comment by AlexHenry666** [comment]
- 单独的html文件样式一直显示没问题。但是concat合并后，生成的`concat.html`中，交互式图表全部都`高度`显示不正常，情况如下图展示。估计与针对concat.html的css样式设定相关，请问具体如何调整。
- https://www.economist.com/graphic-detail/2023/06/07/smoke-blackens-the-air-in-americas-north-east
- https://www.economist.com/finance-and-economics/2023/06/08/amoral-cities-are-flourishing-in-a-turbulent-geopolitical-era

![image](https://github.com/taizihuang/TheEconomist/assets/50627932/d475b172-9690-4a50-ac26-4c5ac3903c16)
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/1976379c-6a34-444b-a3ba-4e7faabafd66)
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/6dfa7970-7a5b-4bd6-83a2-d7129f03f42a)

**Comment by taizihuang** [comment]
> 交互式图表全部都高度显示不正常

已经修复这个bug
