### ISSUE TITLE
contat.html文件显示不完全

### ISSUE THREAD

**Issue by Monkfishare** [taizihuang/TheEconomist#3]
- 新版fetchTe.py下载的concat.html只有封面图，其余文章没有成功按照index.html拼接，查看你下载的concat.html也是同样情况。
- 尝试用旧版代码（如下），可以成功生成完整的contat文件，但有些文章会重复出现。
```
from fetchTE_old import formatAI, genPrint

genPrint()
```
- 总结：可能是新版genPrint生成concat逻辑问题

**Comment by Monkfishare** [comment]
- 报错 downloader.py", line 66, in <lambda>

    url_null += list(df.loc[df.response.map(lambda x: x.find(b'Just a moment')) > 0].url)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
**TypeError: must be str, not bytes**

- 修改成 `url_null += list(df.loc[df.response.map(lambda x: x.decode('utf-8').find('Just a moment')) > 0].url)`不管用

**Comment by taizihuang** [comment]
你这个报错很奇怪，检查一下Downloader生成的pkl文件中的response列是否是二进制数据（理论上应该是的，但是你的报错显示不是）

**Comment by Monkfishare** [comment]
在下载的concat.html中打开图片是正常显示的，确认不是下载原因。但是打印有问题，猜测可能是与CSS的长宽缩放有关，没有100%显示。

**Comment by Monkfishare** [comment]
- 更换多个节点测试，交互图打印显示不正常，发现是网络下载原因。
- 但是很奇怪contact.html打开图片看上去没问题，打印时却出现问题。

**Comment by Monkfishare** [comment]
我这边打印你仓库里下载的concat.html文件，交互图一样显示不正常，烦请确认一哈😄

**Comment by taizihuang** [comment]
我这边打印网页都正常，所以不知道你那边问题出在哪里。

**Comment by Monkfishare** [comment]
1. 原因是没有下载交互图（interacive figure），查看本地html和assets文件夹没有相关离线文件（html，js和css）。打开html能正常看到图片，完全是因为网络在线加载生成的，所以最后打印过程中出现显示不正常也就解释得通了。

2. 关于“downloader.py", line 66  
`url_null += list(df.loc[df.response.map(lambda x: x.find(b'Just a moment')) > 0].url)`  
如果将`find(b'Just a moment')`修改成`find(rb'Just a moment')`二进制，我这边就不会出现报错：**TypeError: must be str, not bytes**，后续能够顺利下载。使用的python版本（3.11.4）

3. 只是交互图（interacive figure）一直无法成功下载，assets文件夹是空的，可能需要优化代码，将交互图单独下载，而非多线程下载，或者增加交互图的下载缓存时间。

**Comment by taizihuang** [comment]
你需要更新一下genTE.py。内嵌网页iframe是单线程下载的，详情见fetchAI(url)函数，记得开全局代理。

**Comment by Monkfishare** [comment]
非常感谢。之前就是用你最新更新的fetchTE.py测试的，是开的全局代理模式，交互图下载失败。还是先老版本用着，毕竟稳定性强😄

**Comment by taizihuang** [comment]
好的，你可以过段时间再试试，没准就好了。

**Comment by Monkfishare** [comment]
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/57531ce4-280e-4cde-82b9-7649120c83ab)
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/87f442c6-4fc7-471b-ac1c-bc00e50657e6)
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/1ba4ebba-9761-43af-9147-f119af47a8f0)
- 图片高度溢出打印页面（图1，图2）
- 图片上方出现大量空白（图3）
- https://www.economist.com/business/2023/08/27/amazon-has-hollywoods-worst-shows-but-its-best-business-model
- https://www.economist.com/business/2023/08/31/the-rise-of-the-asian-activist-investor
- https://www.economist.com/science-and-technology/2023/08/30/some-forms-of-chronic-pain-are-particularly-mysterious

**Comment by Monkfishare** [comment]
![image](https://github.com/taizihuang/TheEconomist/assets/50627932/96c3292f-3776-4cc4-8ae8-6063224e485a)
- 上期的一篇含有交互图的文章，也是图片溢出打印页面
- https://www.economist.com/graphic-detail/2023/08/22/the-sudden-demise-of-indian-vultures-killed-thousands-of-people

**Comment by taizihuang** [comment]
图片问题是因为经济学人有时候会直接在图片里面写入样式。另外，图片太长了是会有被分割的问题，只能通过单面打印解决。

我共享的pdf是尽力做到完全展示内容，排版上面的瑕疵如果不影响阅读，我是觉得可以忽略。当然，我最近在尝试换成LaTeX排版的版本，代码已经写好了，就是pdf.py。你安装whhtmltopdf和texlive后就可以使用了，我打印出来阅读效果还不错。图片显示也正常。

**Comment by taizihuang** [comment]
图片虽然被截掉了，但如果在PDF阅读器里面右键复制，是可以拷贝出完整图片的。
